Options:
  Integration:
    EcoEnchants: false
    AdvancedEnchants: false

Menu:
  Main:
    Title: "EcoEnchant Shop <page>/<max_page>"
    Layout:
      Index:
        - BBBBBBBBB
        - BBBBBBBBB
        - BWWWWWWWB
        - BWWWWWWWB
        - BWWWWWWWB
        - PBBBBBBBN
      Items:
        B:
          Item: BLACK_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: []
          ModelData: 0
        W:
          Item: WHITE_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: []
          ModelData: 0
        N:
          Item: LIME_WOOL
          Amount: 1
          Name: '<green>Next Page'
          Lore: []
          ModelData: 0
        P:
          Item: RED_WOOL
          Amount: 1
          Name: '<red>Previous Page'
          Lore: []
          ModelData: 0
          #EXAMPLE CASE FOR HEADS
          #H:
          #Item: PLAYER_HEAD
          #Amount: 1
          #Name: ''
          #Lore: []
          #ModelData: 0
          #HeadValue: YOUR_HEAD_VALUE
          #D
          #Item: HeadDatabase
          #Amount: 1
          #Name: ''
          #Lore: []
          #ModelData: 0
          #HeadDatabase: HDB_ID
      EnchantmentSlots: [19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 37, 38, 39, 40, 41, 42, 43]
      NextPageSlots: [53]
      PreviousPageSlots: [45]
      BackSlots: [ 49 ]
      ItemSearchSlot: 4
  Level:
    Title: "Select Level"
    Layout:
      Index:
        - BBBBBBBBB
        - BWWWWWWWB
        - BWWWWWWWB
        - BWWWWWWWB
        - BBBBBBBBB
      Items:
        B:
          Item: BLACK_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: []
          ModelData: 0
        W:
          Item: WHITE_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: []
          ModelData: 0
      LevelSlots: [ 10, 11, 12, 13, 14, 15, 16, 19, 20, 21, 22, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34 ]
  Confirm:
    Title: "Order Confirmation"
    Layout:
      Index:
        - BBBBBBBBB
        - BPWWWWWNB
        - BBBBBBBBB
      Items:
        B:
          Item: BLACK_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: [ ]
          ModelData: 0
        W:
          Item: WHITE_STAINED_GLASS_PANE
          Amount: 1
          Name: ''
          Lore: [ ]
          ModelData: 0
        N:
          Item: LIME_WOOL
          Amount: 1
          Name: '<green>Confirm Transaction'
          Lore: [ ]
          ModelData: 0
        P:
          Item: RED_WOOL
          Amount: 1
          Name: '<red>Deny Transaction'
          Lore: [ ]
          ModelData: 0
      PreviewSlot: 13
      AcceptSlots: [ 16 ]
      DenySlots: [ 10 ]

ItemTemplate:
  Enchantment:
    Name: '<yellow><name>'
    Lore:
      - "<description>"
      - ""
      - "<white>Rarity: <rarity>"
      - "<white>Max Level: <green><max_level>"
      - "<white>Applicable to: <green><applicable>"
      - "<white>Conflicts With: <conflicts>"
      - ""
      - "<white>Price: <price>"
    Rarity:
      Common: '<gray>Common'
      Uncommon: '<gray>Uncommon'
      Rare: '<aqua>Rare'
      Epic: '<light_purple>Epic'
      Legendary: '<gold>Legendary'
      Special: '<blue>Special'
      VerySpecial: '<rainbow>Very Special</rainbow>'
    Conflicts:
      NoConflicts: '<green>No Conflict'
      Everything: '<red>Every Enchantments'
    Price:
      Single: '<yellow>$<price>'
      Multiple: '<yellow>$<min_price> - $<max_price>'

