name: EcoEnchantShop
version: '${version}'
main: com.teenkung.ecoenchantshop.EcoEnchantShop
api-version: '1.20'
dependency:
  - EcoEnchants
  - eco

commands:
  ecoenchantshop:
    permissions: ecoenchantshop.use
    aliases: ees