name: EcoEnchantShop
version: '${version}'
main: com.teenkung.ecoenchantshop.EcoEnchantShop
api-version: '1.20'
dependency:
  - EcoEnchants
  - eco
  - NBTAPI
  - Vault
  
softdepend:
  - HeadDatabase

commands:
  ecoenchantshop:
    permissions: ecoenchantshop.use
    aliases: ees